const $=s=>document.querySelector(s);
const icons={"Astral Fox":"🦊","Moss Golem":"🌿","Volt Drake":"🐉","Moon Sage":"🌙","Ember Knight":"🔥","Crystal Wisp":"💎","Tidal Serpent":"🌊","Dawn Sprite":"✨","Solar Titan":"☀️","Void Dragon":"🐲","Star Emperor":"👑","Cosmic Phoenix":"🦅"};
const originalDeck=[{name:'Astral Fox',level:1,type:'monster',atk:900,def:700},{name:'Moss Golem',level:3,type:'monster',atk:1200,def:1500},{name:'Volt Drake',level:5,type:'monster',atk:1800,def:1100},{name:'Moon Sage',level:4,type:'monster',atk:1400,def:1700},{name:'Ember Knight',level:6,type:'monster',atk:1600,def:1000},{name:'Crystal Wisp',level:2,type:'monster',atk:700,def:500},{name:'Tidal Serpent',level:8,type:'monster',atk:2000,def:1200},{name:'Dawn Sprite',level:7,type:'monster',atk:800,def:900},{name:'Solar Titan',level:10,type:'monster',atk:2700,def:2200},{name:'Void Dragon',level:12,type:'monster',atk:3200,def:2600},{name:'Star Emperor',level:9,type:'monster',atk:2400,def:2100},{name:'Cosmic Phoenix',level:11,type:'monster',atk:2900,def:1800}];
let state;
const tributeCost=level=>level<=4?0:level<=6?1:level<=9?2:3;
function freshState(){return{playerLP:4000,enemyLP:4000,deck:[...originalDeck],hand:[],playerField:Array(5).fill(null),enemyField:Array(5).fill(null).map((_,i)=>i===2?{...originalDeck[2],faceDown:true}:null),selected:null,selectedTributes:[],turn:1,over:false}}
function stars(level){return'★'.repeat(level)}
function cardHTML(c,field=false){const stats=`<div class="stats"><span>ATK ${c.atk}</span><span>DEF ${c.def}</span></div>`;return`<div class="card monster ${field?'field-card':'hand-card'} ${c.faceDown?'face-down':''}" title="${c.name} · ${c.level} sao"><div class="card-art">${c.faceDown?'':icons[c.name]}</div>${c.faceDown?'':`<div style="position:absolute;top:2px;left:2px;right:2px;text-align:center;color:#ffd96b;font-size:6px;letter-spacing:-1px">${stars(c.level)}</div><div class="card-name">${c.name}</div>${stats}`}</div>`}
function log(text,cls=''){const e=document.createElement('div');e.className=`log-line ${cls}`;e.innerHTML=text;$('#log').prepend(e)}
function drawCard(){if(state.deck.length)state.hand.push(state.deck.shift());else log('<b>Bộ bài đã hết!</b>','damage')}
function zoneHTML(card,type,i){return`<div class="zone ${card?'occupied':'empty'}" data-zone="${type}" data-slot="${i}">${card?cardHTML(card,true):`<b>＋</b><small>${type==='monster'?'QUÁI THÚ':'PHÉP / BẪY'}</small>`}</div>`}
function render(){
 $('#playerLP').textContent=state.playerLP;$('#enemyLP').textContent=state.enemyLP;$('#playerLifeBar').style.width=Math.max(0,state.playerLP/40)+'%';$('#enemyLifeBar').style.width=Math.max(0,state.enemyLP/40)+'%';$('#deckCount').textContent=state.deck.length+' lá còn lại';$('#handCount').textContent=state.hand.length;$('#hand').innerHTML=state.hand.map(c=>cardHTML(c)).join('');
 $('#playerMonsterSlots').innerHTML=state.playerField.map((c,i)=>zoneHTML(c,'monster',i)).join('');$('#enemyMonsterSlots').innerHTML=state.enemyField.map((c,i)=>zoneHTML(c,'enemy-monster',i)).join('');$('#playerSpellSlots').innerHTML=Array.from({length:5},(_,i)=>zoneHTML(null,'spell',i)).join('');$('#enemySpellSlots').innerHTML=Array.from({length:5},(_,i)=>zoneHTML(null,'enemy-spell',i)).join('');
 document.querySelectorAll('#hand .card').forEach((e,i)=>e.onclick=()=>selectCard(i));document.querySelectorAll('#playerMonsterSlots .zone').forEach(e=>{const i=+e.dataset.slot;e.onclick=()=>state.playerField[i]?toggleTribute(i):summon(i);const c=e.querySelector('.card');if(c)c.onclick=x=>{x.stopPropagation();toggleTribute(i)}});
}
function selectCard(i){if(state.over)return;state.selected=state.selected===i?null:i;state.selectedTributes=[];document.querySelectorAll('#hand .card').forEach((e,n)=>e.classList.toggle('selected',n===state.selected));document.querySelectorAll('#playerMonsterSlots .empty').forEach(e=>e.classList.toggle('target',state.selected!==null));$('#hint').textContent=state.selected===null?'Chọn bài quái trên tay, sau đó chọn một ô quái thú.':'Chọn ô quái thú trống để triệu hồi; chọn quái trên sân để hiến tế.'}
function toggleTribute(i){if(state.selected===null)return;const cost=tributeCost(state.hand[state.selected].level);if(!cost){showToast('Lá này không cần hiến tế');return}if(state.selectedTributes.includes(i))state.selectedTributes=state.selectedTributes.filter(x=>x!==i);else if(state.selectedTributes.length<cost)state.selectedTributes.push(i);else showToast(`Cần đúng ${cost} quái hiến tế`);render();$('#hint').textContent=`Đã chọn ${state.selectedTributes.length}/${cost} quái hiến tế. Chọn ô trống để triệu hồi.`}
function summon(slot){if(state.selected===null||state.playerField[slot]||state.over)return;const card=state.hand[state.selected],cost=tributeCost(card.level);if(state.selectedTributes.length<cost){log(`<b>${card.name}</b> cấp ${card.level} sao cần hiến tế <b>${cost}</b> quái thú.`,'damage');showToast(`Cần hiến tế ${cost} quái thú`);return}state.selectedTributes.sort((a,b)=>b-a).forEach(i=>{const old=state.playerField.splice(i,1)[0];log(`Hiến tế <b>${old.name}</b> (${old.level}★).`)});const adjusted=state.selectedTributes.filter(i=>i<slot).length;state.playerField.splice(slot-adjusted,0,state.hand.splice(state.selected,1)[0]);const summoned=state.playerField[slot-adjusted];state.selected=null;state.selectedTributes=[];log(`<b>Bạn</b> triệu hồi ${summoned.name} (${summoned.level}★).`);render()}
function enemyTurn(){if(state.over)return;log('<b>Oracle AI</b> đang suy nghĩ...');setTimeout(()=>{const live=state.playerField.filter(Boolean);const hit=live.length?Math.max(0,850-live[0].atk):300;state.playerLP-=hit;log(`<b>Oracle AI</b> tấn công, gây <b>${hit}</b> sát thương.`,'damage');state.turn++;drawCard();state.over=state.playerLP<=0||state.enemyLP<=0;if(state.over)log(state.playerLP<=0?'<b>Bạn đã thất bại.</b>':'<b>Bạn chiến thắng!</b>');else log(`<b>Lượt ${state.turn}</b> bắt đầu. Bạn đã rút một lá.`);render()},650)}
function endTurn(){if(state.over)return;const attacker=state.playerField.filter(Boolean)[0];const target=state.enemyField.filter(Boolean)[0];if(attacker){const damage=target?Math.max(0,attacker.atk-target.atk):attacker.atk;state.enemyLP-=damage;log(`<b>${attacker.name}</b> tấn công và gây <b>${damage}</b> sát thương.`,'damage')}else log('Bạn chưa có quái thú trên sân.');if(state.enemyLP<=0){state.over=true;log('<b>Bạn chiến thắng!</b>');render();return}render();enemyTurn()}
function start(){state=freshState();for(let i=0;i<3;i++)drawCard();$('#log').innerHTML='';log('<b>Trận đấu bắt đầu!</b>');log('Sân có 28 ô riêng của hai bên và 2 ô đặc biệt ở giữa.');render()}
$('#endTurnBtn').onclick=endTurn;$('#newGameBtn').onclick=start;$('#soundBtn').onclick=()=>showToast('Âm thanh đã tắt/bật');function showToast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1500)}start();
