const $ = (s) => document.querySelector(s);
const icons = {"Astral Fox":"🦊","Moss Golem":"🌿","Volt Drake":"🐉","Moon Sage":"🌙","Ember Knight":"🔥","Crystal Wisp":"💎","Tidal Serpent":"🌊","Dawn Sprite":"✨","Solar Titan":"☀️","Void Dragon":"🐲","Star Emperor":"👑","Cosmic Phoenix":"🦅"};
const originalDeck = [
  {name:'Astral Fox',level:1,type:'monster',atk:900,def:700,desc:'Linh thú tinh tú'},
  {name:'Moss Golem',level:3,type:'monster',atk:1200,def:1500,desc:'Người đá rêu'},
  {name:'Volt Drake',level:5,type:'monster',atk:1800,def:1100,desc:'Long thú sấm sét'},
  {name:'Moon Sage',level:4,type:'monster',atk:1400,def:1700,desc:'Hiền giả mặt trăng'},
  {name:'Ember Knight',level:6,type:'monster',atk:1600,def:1000,desc:'Kỵ sĩ tro hồng'},
  {name:'Crystal Wisp',level:2,type:'monster',atk:700,def:500,desc:'Tinh linh pha lê'},
  {name:'Tidal Serpent',level:8,type:'monster',atk:2000,def:1200,desc:'Xà thần thủy triều'},
  {name:'Dawn Sprite',level:7,type:'monster',atk:800,def:900,desc:'Tinh linh bình minh'},
  {name:'Solar Titan',level:10,type:'monster',atk:2700,def:2200,desc:'Titan mặt trời'},
  {name:'Void Dragon',level:12,type:'monster',atk:3200,def:2600,desc:'Long thần hư không'},
  {name:'Star Emperor',level:9,type:'monster',atk:2400,def:2100,desc:'Đế vương tinh tú'},
  {name:'Cosmic Phoenix',level:11,type:'monster',atk:2900,def:1800,desc:'Phượng hoàng vũ trụ'}
];
let state;
function tributeCost(level){return level<=4?0:level<=6?1:level<=9?2:3}
function freshState(){return{playerLP:4000,enemyLP:4000,deck:[...originalDeck],hand:[],playerField:[],enemyField:[{...originalDeck[2],faceDown:true}],selected:null,selectedTributes:[],turn:1,over:false}}
function stars(level){return '★'.repeat(level)}
function cardHTML(c,field=false){const stats=c.type==='monster'?`<div class="stats"><span>ATK ${c.atk}</span><span>DEF ${c.def}</span></div>`:'';return`<div class="card ${c.type} ${field?'field-card':'hand-card'} ${c.faceDown?'face-down':''}" data-name="${c.name}" title="${c.name} · Cấp ${c.level} sao"><div class="card-art">${c.faceDown?'':icons[c.name]}</div>${c.faceDown?'':`<div class="card-name">${c.name}</div><div style="position:absolute;top:3px;left:4px;right:4px;text-align:center;color:#ffd96b;font-size:8px;letter-spacing:-1px;text-shadow:0 0 5px #ff9d3d">${stars(c.level)}</div>${stats}`}</div>`}
function log(text,cls=''){const el=document.createElement('div');el.className=`log-line ${cls}`;el.innerHTML=text;$('#log').prepend(el)}
function drawCard(){if(!state.deck.length){log('<b>Bộ bài đã hết!</b>','damage');return}state.hand.push(state.deck.shift())}
function render(){
 $('#playerLP').textContent=state.playerLP;$('#enemyLP').textContent=state.enemyLP;$('#playerLifeBar').style.width=`${Math.max(0,state.playerLP/40)}%`;$('#enemyLifeBar').style.width=`${Math.max(0,state.enemyLP/40)}%`;$('#deckCount').textContent=`${state.deck.length} lá còn lại`;$('#handCount').textContent=state.hand.length;
 $('#hand').innerHTML=state.hand.map(c=>cardHTML(c)).join('');
 $('#playerSlots').innerHTML=Array.from({length:5},(_,i)=>{const c=state.playerField[i];const selected=c&&state.selectedTributes.includes(i);return`<div class="slot ${c?'occupied':'empty'}" data-slot="${i}" style="${selected?'border-color:#ffcf68;box-shadow:0 0 20px #ffbd4c;background:#ffbd4c22':''}">${c?cardHTML(c,true):''}</div>`}).join('');
 $('#enemySlots').innerHTML=Array.from({length:5},(_,i)=>`<div class="slot ${state.enemyField[i]?'occupied':'empty'}">${state.enemyField[i]?cardHTML(state.enemyField[i],true):''}</div>`).join('');
 document.querySelectorAll('#hand .card').forEach((el,i)=>el.onclick=()=>selectCard(i));
 document.querySelectorAll('#playerSlots .slot').forEach(el=>{el.onclick=()=>summon(Number(el.dataset.slot));const card=el.querySelector('.card');if(card)card.onclick=(event)=>{event.stopPropagation();toggleTribute(Number(el.dataset.slot))}});
}
function selectCard(i){if(state.over)return;state.selected=state.selected===i?null:i;state.selectedTributes=[];document.querySelectorAll('#hand .card').forEach((c,n)=>c.classList.toggle('selected',n===state.selected));$('#hint').textContent=state.selected===null?'Chọn một lá trên tay, sau đó triệu hồi vào ô trống.':'Chọn quái thú trên sân để hiến tế nếu lá này từ cấp 5 sao trở lên, hoặc chọn ô trống để triệu hồi.';document.querySelectorAll('#playerSlots .empty').forEach(s=>s.classList.toggle('target',state.selected!==null))}
function toggleTribute(slot){if(state.selected===null||state.over)return;const card=state.playerField[slot];if(!card)return;const cost=tributeCost(state.hand[state.selected].level);if(cost===0){showToast('Lá này không cần hiến tế');return}if(state.selectedTributes.includes(slot))state.selectedTributes=state.selectedTributes.filter(x=>x!==slot);else if(state.selectedTributes.length<cost)state.selectedTributes.push(slot);else showToast(`Lá cấp ${state.hand[state.selected].level} sao cần đúng ${cost} lá hiến tế`);render();$('#hint').textContent=`Đã chọn ${state.selectedTributes.length}/${cost} quái thú hiến tế. Nhấn vào ô trống để triệu hồi.`}
function summon(slot){if(state.selected===null||state.playerField[slot]||state.over)return;const card=state.hand[state.selected];const cost=tributeCost(card.level);if(state.selectedTributes.length<cost){log(`<b>${card.name}</b> cấp ${card.level} sao cần hiến tế <b>${cost}</b> quái thú trên sân.`,'damage');showToast(`Cần hiến tế ${cost} quái thú`);return}state.selectedTributes.sort((a,b)=>b-a).forEach(i=>{const sacrificed=state.playerField.splice(i,1)[0];log(`Hiến tế <b>${sacrificed.name}</b> (${sacrificed.level}★).`)});const adjustedSlot=state.selectedTributes.filter(i=>i<slot).length;const summoned=state.hand.splice(state.selected,1)[0];state.playerField.splice(slot-adjustedSlot,0,summoned);state.selected=null;state.selectedTributes=[];log(`<b>Bạn</b> triệu hồi ${summoned.name} (${summoned.level}★).`);$('#hint').textContent='Quái thú đã sẵn sàng. Kết thúc lượt để giao chiến.';render()}
function enemyTurn(){if(state.over)return;log('<b>Oracle AI</b> đang suy nghĩ...');setTimeout(()=>{const live=state.playerField.filter(Boolean);if(live.length){const target=live[0],hit=Math.max(0,850-target.atk);state.playerLP-=hit;log(`<b>Oracle AI</b> tấn công, gây <b>${hit}</b> sát thương.`,'damage')}else{state.playerLP-=300;log('<b>Oracle AI</b> tấn công trực tiếp, gây <b>300</b> sát thương.','damage')}state.turn++;drawCard();state.over=state.playerLP<=0||state.enemyLP<=0;if(state.over){log(state.playerLP<=0?'<b>Bạn đã thất bại.</b>':'<b>Bạn chiến thắng!</b>');$('#turnBanner').textContent=state.playerLP<=0?'DEFEAT':'VICTORY'}else{log(`<b>Lượt ${state.turn}</b> bắt đầu. Bạn đã rút một lá.`);$('#turnBanner').textContent=`LƯỢT ${state.turn} CỦA BẠN · MAIN PHASE`}render()},650)}
function endTurn(){if(state.over)return;const attacker=state.playerField.filter(Boolean)[0];if(attacker){const target=state.enemyField.filter(Boolean)[0];if(target){const damage=Math.max(0,attacker.atk-target.atk);state.enemyLP-=damage;log(`<b>${attacker.name}</b> giao chiến và gây <b>${damage}</b> sát thương.`,damage?'damage':'')}else{state.enemyLP-=attacker.atk;log(`<b>${attacker.name}</b> tấn công trực tiếp! <b>-${attacker.atk}</b> LP.`,'damage')}}else log('Bạn chưa có quái thú trên sân.');if(state.enemyLP<=0){state.over=true;log('<b>Bạn chiến thắng!</b>');$('#turnBanner').textContent='VICTORY';render();return}$('#turnBanner').textContent='LƯỢT ĐỐI THỦ · BATTLE PHASE';render();enemyTurn()}
function start(){state=freshState();for(let i=0;i<3;i++)drawCard();$('#log').innerHTML='';log('<b>Trận đấu bắt đầu!</b> Rút 3 lá để khởi động.');log('Luật triệu hồi: 1–4★ tự triệu hồi · 5–6★ hiến tế 1 · 7–9★ hiến tế 2 · 10–12★ hiến tế 3.');$('#turnBanner').textContent='LƯỢT CỦA BẠN · MAIN PHASE';render()}
$('#endTurnBtn').onclick=endTurn;$('#newGameBtn').onclick=start;$('#soundBtn').onclick=()=>showToast('Âm thanh đã tắt/bật');function showToast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1500)}start();
